INSERT INTO [dbo].[Role] VALUES ('超级管理员',1,GETDATE(),'超级管理员',GETDATE())
INSERT INTO [dbo].[Right] VALUES ('查询',1,GETDATE(),GETDATE())
INSERT INTO [dbo].[Right] VALUES ('添加',1,GETDATE(),GETDATE())
INSERT INTO [dbo].[Right] VALUES ('修改',1,GETDATE(),GETDATE())
INSERT INTO [dbo].[Right] VALUES ('删除',1,GETDATE(),GETDATE())
INSERT INTO [dbo].[Right] VALUES ('导入',1,GETDATE(),GETDATE())
INSERT INTO [dbo].[Right] VALUES ('导出',1,GETDATE(),GETDATE())
INSERT INTO [dbo].[Column] VALUES ('系统配置','','icon icon-102',0,0,1,GETDATE(),GETDATE(),'系统配置')
INSERT INTO [dbo].[Column] VALUES ('用户管理','','icon icon-219',0,0,1,GETDATE(),GETDATE(),'用户管理')
INSERT INTO [dbo].[Column] VALUES ('栏目管理','/Basic/ColumnManage.aspx','icon icon-22',0,0,1,GETDATE(),GETDATE(),'系统配置-栏目管理')
INSERT INTO [dbo].[Column] VALUES ('权限管理','/UserManage/RightManage.aspx','icon icon-268',2,0,1,GETDATE(),GETDATE(),'用户管理-权限管理')
INSERT INTO [dbo].[Column] VALUES ('角色管理','/UserManage/RoleManage.aspx','icon icon-425',2,0,1,GETDATE(),GETDATE(),'用户管理-角色管理')
INSERT INTO [dbo].[Column] VALUES ('用户管理','/UserManage/UserManage.aspx','icon icon-486',2,0,1,GETDATE(),GETDATE(),'用户管理-用户管理')
INSERT INTO [dbo].[ColumnRight] VALUES (1,1)
INSERT INTO [dbo].[ColumnRight] VALUES (2,1)
INSERT INTO [dbo].[ColumnRight] VALUES (3,1)
INSERT INTO [dbo].[ColumnRight] VALUES (4,1)
INSERT INTO [dbo].[ColumnRight] VALUES (5,1)
INSERT INTO [dbo].[ColumnRight] VALUES (6,1)
INSERT INTO [dbo].[RoleRight] VALUES (1,1,1)
INSERT INTO [dbo].[RoleRight] VALUES (1,2,1)
INSERT INTO [dbo].[RoleRight] VALUES (1,3,1)
INSERT INTO [dbo].[RoleRight] VALUES (1,4,1)
INSERT INTO [dbo].[RoleRight] VALUES (1,5,1)
INSERT INTO [dbo].[RoleRight] VALUES (1,6,1)
INSERT INTO [dbo].[User] VALUES (0,'host','C4CA4238A0B923820DCC509A6F75849B','超级管理员','',1,'','','','',GETDATE(),'','',0,0,GETDATE(),1)